spring:
  profiles:
    active: local
  config:
    import:
      - classpath:secrets/Maple-Trend-Secret/common/application.yaml
      - classpath:secrets/Maple-Trend-Secret/nexon-open-api-core/application.yaml
      - classpath:secrets/Maple-Trend-Secret/app-maple-stamp-api/application.yaml
