spring:
  config:
    import:
      - classpath:copied-secrets/Maple-Trend-Secret/common/application.yaml
      - classpath:copied-secrets/Maple-Trend-Secret/maple-stamp-domain-mariadb/application.yaml