spring:
  application:
    name: maple-stamp-api
server:
  address: 0.0.0.0
  port: 9000
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'maple-trend-be'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9000' ]
management:
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, prometheus
        exclude: env, beans
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}
