spring:
  profiles:
    active: "local"
  # 테이블 자동 생성 및 수정
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      # camelCase -> snake_case
      physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        connection:
          charset: utf8
          characterEncoding: utf8
          useUnicode: true
        format_sql: true # hibernate query 포맷 정리
        show_sql: true # hibernate query를 콘솔에 출력
---
# 테스트 프로필
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}
    username: {DB_USER}
    password: {DB_PASSWORD}
---
# 로컬 프로필
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}
    username: {DB_USER}
    password: {DB_PASSWORD}
---
# 운영 프로필
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{DB_HOST}
    username: {DB_USER}
    password: {DB_PASSWORD}