# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Gradle Build and Deploy

on:
  push:
    branches-ignore: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHP_TOKEN }}
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          gradle-version: release-candidate
          cache-disabled: true
          arguments: build --scan

      - uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          repo: ${{ github.repository }}
          submodules: true

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hyyena/maple-trend
          stage: main
          yaml: |
            name: maple-trend-be
            app: java@19
            options:
              ports: "9000"
              healthz: /actuator/health
              strategy: rolling
              include: app-maple-stamp-api
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              